// Autogenerated from .soy file by soy2js
declare module "StarDistanceMap/widget.soy" {
	function widget(state:any):any;
	function gene_groups(state:any):any;
	function genes(state:any):any;
	function gene(state:any):any;
	function gene_dropper(state:any):any;
	function gene_distance_dropper(state:any):any;
	function chromosomes(state:any):any;
	function chromosome(state:any):any;
	function gene_distance(state:any):any;
}
declare function widget(state:any):any;
declare function gene_groups(state:any):any;
declare function genes(state:any):any;
declare function gene(state:any):any;
declare function gene_dropper(state:any):any;
declare function gene_distance_dropper(state:any):any;
declare function chromosomes(state:any):any;
declare function chromosome(state:any):any;
declare function gene_distance(state:any):any;
