// Autogenerated from .soy file by soy2js
declare module "i18n_example/en/localized.soy" {
	function switch(state:any):any;
	function test(state:any):any;
	function world(state:any):any;
	function is(state:any):any;
}
declare function switch(state:any):any;
declare function test(state:any):any;
declare function world(state:any):any;
declare function is(state:any):any;
