// Autogenerated from .soy file by soy2js
declare module "soy_example/test.soy" {
	function helloWorld(state:any):any;
	function footer(state:any):any;
}
declare function helloWorld(state:any):any;
declare function footer(state:any):any;
