// Autogenerated from .soy file by soy2js
declare module "StarGenetics_Obsolete/selectexperiment.soy" {
	function select_experiments(state:any):any;
}
declare function select_experiments(state:any):any;
