// Autogenerated from .soy file by soy2js
declare module "StarGenetics_Obsolete/stargeneticsws.soy" {
	function before_open(state:any):any;
	function onopen(state:any):any;
	function footer(state:any):any;
}
declare function before_open(state:any):any;
declare function onopen(state:any):any;
declare function footer(state:any):any;
