// Autogenerated from .soy file by soy2js
declare module "i18n_example/ne/test.soy" {
	function helloWorld(state:any):any;
	function sum(state:any):any;
	function next_language(state:any):any;
}
declare function helloWorld(state:any):any;
declare function sum(state:any):any;
declare function next_language(state:any):any;
