// Autogenerated from .soy file by soy2js
declare module "StarPedigree/widget_template.css.soy" {
	function css_html(state:any):any;
	function css_text(state:any):any;
}
declare function css_html(state:any):any;
declare function css_text(state:any):any;
