// Autogenerated from .soy file by soy2js
declare module "StarPedigree/widget_template.soy" {
	function wrapper(state:any):any;
	function render_generations(state:any):any;
	function render_individuals(state:any):any;
	function render_relationships(state:any):any;
	function render_relationship(state:any):any;
	function render_parental_link(state:any):any;
	function render_children_links(state:any):any;
}
declare function wrapper(state:any):any;
declare function render_generations(state:any):any;
declare function render_individuals(state:any):any;
declare function render_relationships(state:any):any;
declare function render_relationship(state:any):any;
declare function render_parental_link(state:any):any;
declare function render_children_links(state:any):any;
