// Autogenerated from .soy file by soy2js
declare module "StarGenetics/sg_client_mainframe.soy" {
	function main(state:any):any;
	function workspace(state:any):any;
	function io(state:any):any;
	function strain(state:any):any;
	function strain_short(state:any):any;
	function strain_place_holder(state:any):any;
	function strains(state:any):any;
	function new_experiment(state:any):any;
	function all_experiments(state:any):any;
}
declare function main(state:any):any;
declare function workspace(state:any):any;
declare function io(state:any):any;
declare function strain(state:any):any;
declare function strain_short(state:any):any;
declare function strain_place_holder(state:any):any;
declare function strains(state:any):any;
declare function new_experiment(state:any):any;
declare function all_experiments(state:any):any;
