// Autogenerated from .soy file by soy2js
declare module "StarGenetics/sg_client_mainframe.soy" {
	function gwt_content(state:any):any;
	function main(state:any):any;
	function workspace(state:any):any;
	function io(state:any):any;
	function strain(state:any):any;
	function strain_short(state:any):any;
	function strain_place_holder(state:any):any;
	function strains(state:any):any;
	function new_experiment_expanded(state:any):any;
	function new_experiment(state:any):any;
	function all_experiments(state:any):any;
	function one_experiment(state:any):any;
	function sex_icon(state:any):any;
	function male_icon(state:any):any;
	function female_icon(state:any):any;
}
declare function gwt_content(state:any):any;
declare function main(state:any):any;
declare function workspace(state:any):any;
declare function io(state:any):any;
declare function strain(state:any):any;
declare function strain_short(state:any):any;
declare function strain_place_holder(state:any):any;
declare function strains(state:any):any;
declare function new_experiment_expanded(state:any):any;
declare function new_experiment(state:any):any;
declare function all_experiments(state:any):any;
declare function one_experiment(state:any):any;
declare function sex_icon(state:any):any;
declare function male_icon(state:any):any;
declare function female_icon(state:any):any;
